#!/bin/bash
echo
echo "WiringPi for Pine64 is now installed"
echo "Please check the wiki: "
echo "For extra references:"
echo "Github: https://github.com/hardkernel/wiringPi"
echo "Examples folder is copied to /usr/share/wiringPi/examples"
